import { and, eq, isNull } from "drizzle-orm";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { WebStandardStreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js";
import { z } from "zod";
import { createEmptyCard } from "ts-fsrs";
import { getDb } from "../../../db";
import { apiKeys } from "../../../db/schema";
import { loadSnapshot, saveSnapshot } from "../../../lib/snapshot-store";

async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function authenticate(request:Request){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token?.startsWith("lexique_sk_"))return null;const [key]=await getDb().select().from(apiKeys).where(and(eq(apiKeys.keyHash,await sha256(token)),isNull(apiKeys.revokedAt))).limit(1);if(!key)return null;await getDb().update(apiKeys).set({lastUsedAt:new Date().toISOString()}).where(eq(apiKeys.id,key.id));return key.userId}
async function load(userId:string){const payload=await loadSnapshot(userId);return payload?JSON.parse(payload):{notes:[],cards:[],logs:[],decks:[{id:"tef",name:"TEF essentiel",description:"TEF Canada vocabulary"}]}}
async function save(userId:string,state:any){await saveSnapshot(userId,JSON.stringify(state))}
const bare=(v:string)=>v.trim().toLowerCase().normalize("NFC").replace(/^(le|la|les|un|une|des|l’|l')\s*/i,"");
const content=(value:unknown)=>({content:[{type:"text" as const,text:JSON.stringify(value)}]});

function createServer(userId:string){const server=new McpServer({name:"lexique",version:"1.0.0"});
  const addWords=async(words:(string|Record<string,unknown>)[],deck="TEF essentiel",tags:string[]=[] )=>{const state=await load(userId);state.notes??=[];state.cards??=[];const created:string[]=[];const merged:string[]=[];for(const item of words){const input=typeof item==="string"?{lemma:item}:item;const lemma=String(input.lemma??input.word??"").trim();if(!lemma)continue;const found=state.notes.find((n:any)=>bare(n.lemma)===bare(lemma)&&n.deck===deck);if(found){Object.assign(found,Object.fromEntries(Object.entries(input).filter(([,v])=>v!==undefined&&v!==null&&v!=="")));found.tags=[...new Set([...(found.tags??[]),...tags])];merged.push(found.id);continue}const id=crypto.randomUUID();const article=/^(le|la|un|une)\s/i.test(lemma)?lemma.split(" ")[0]:"";const note={id,lemma,article,gender:input.gender??(["la","une"].includes(article)?"feminine":article?"masculine":null),part:input.partOfSpeech??input.part??"needs review",translation:input.translation??input.meaning??"needs review",exampleFr:input.exampleSentenceFr??"",exampleEn:input.exampleSentenceEn??"",ipa:input.ipa??"",deck,tags:[...new Set([...(Array.isArray(input.tags)?input.tags:[]),...tags])],cefr:input.cefrLevel??"—",needsReview:!input.translation};state.notes.push(note);const kinds=["PRODUCTION","RECOGNITION","LISTENING",...(note.gender?["GENDER"]:[]),...(note.exampleFr?["CLOZE"]:[])];state.cards.push(...kinds.map(kind=>({id:`${id}-${kind}`,noteId:id,kind,memory:createEmptyCard(new Date()),lapses:0,successes:0,suspended:false})));created.push(id)}await save(userId,state);return{created,merged}}
  server.registerTool("add_words",{description:"Add one or many French words, merge duplicates, and generate atomic review cards.",inputSchema:{words:z.array(z.union([z.string(),z.record(z.string(),z.unknown())])),deck:z.string().optional(),tags:z.array(z.string()).optional(),autoEnrich:z.boolean().optional()}},async({words,deck,tags})=>content(await addWords(words,deck,tags)));
  server.registerTool("add_note",{description:"Create one detailed French lexical note.",inputSchema:{lemma:z.string(),translation:z.string(),deck:z.string().optional(),article:z.string().optional(),gender:z.string().nullable().optional(),partOfSpeech:z.string().optional(),ipa:z.string().optional(),exampleSentenceFr:z.string().optional(),exampleSentenceEn:z.string().optional(),tags:z.array(z.string()).optional()}},async(input)=>content(await addWords([input],input.deck,input.tags)));
  server.registerTool("search_notes",{description:"Search the user's notes by lemma, meaning, example, deck, or tags.",inputSchema:{query:z.string(),deck:z.string().optional(),tags:z.array(z.string()).optional(),limit:z.number().int().min(1).max(100).optional()}},async({query,deck,tags,limit=20})=>{const s=await load(userId),q=bare(query);return content({notes:(s.notes??[]).filter((n:any)=>(!deck||n.deck===deck)&&(!tags?.length||tags.every(t=>n.tags?.includes(t)))&&JSON.stringify(n).toLowerCase().includes(q)).slice(0,limit)})});
  server.registerTool("update_note",{description:"Update a note's verified lexical information.",inputSchema:{id:z.string(),patch:z.record(z.string(),z.unknown())}},async({id,patch})=>{const s=await load(userId),n=s.notes?.find((x:any)=>x.id===id);if(!n)throw new Error("Note not found");Object.assign(n,patch);await save(userId,s);return content({updated:id})});
  server.registerTool("delete_notes",{description:"Soft-delete notes from the active deck.",inputSchema:{ids:z.array(z.string()).min(1)}},async({ids})=>{const s=await load(userId),now=new Date().toISOString();for(const n of s.notes??[])if(ids.includes(n.id))n.deletedAt=now;for(const c of s.cards??[])if(ids.includes(c.noteId))c.suspended=true;await save(userId,s);return content({deleted:ids})});
  server.registerTool("list_decks",{description:"List decks with note and due-card counts.",inputSchema:{}},async()=>{const s=await load(userId),names=[...new Set((s.notes??[]).filter((n:any)=>!n.deletedAt).map((n:any)=>String(n.deck)))];return content({decks:names.map(name=>({name,notes:s.notes.filter((n:any)=>n.deck===name&&!n.deletedAt).length,due:s.cards.filter((c:any)=>{const n=s.notes.find((x:any)=>x.id===c.noteId);return n?.deck===name&&!c.suspended&&new Date(c.memory.due)<=new Date()}).length}))})});
  server.registerTool("create_deck",{description:"Create a named French study deck.",inputSchema:{name:z.string(),description:z.string().optional()}},async({name,description=""})=>{const s=await load(userId);s.decks??=[];const existing=s.decks.find((d:any)=>d.name.toLowerCase()===name.toLowerCase());if(existing)return content({deck:existing,created:false});const deck={id:crypto.randomUUID(),name,description};s.decks.push(deck);await save(userId,s);return content({deck,created:true})});
  server.registerTool("get_due_summary",{description:"Return the user's due, new, and streak summary.",inputSchema:{deck:z.string().optional()}},async({deck})=>{const s=await load(userId),notes=new Map((s.notes??[]).map((n:any)=>[n.id,n]));const cards=(s.cards??[]).filter((c:any)=>!c.suspended&&(!deck||(notes.get(c.noteId) as any)?.deck===deck));return content({dueNow:cards.filter((c:any)=>new Date(c.memory.due)<=new Date()).length,newAvailable:cards.filter((c:any)=>c.memory.state===0).length,reviews:(s.logs??[]).length})});
  server.registerTool("get_struggling_cards",{description:"Return cards with the most lapses and weakest stability.",inputSchema:{limit:z.number().int().min(1).max(100).optional(),deck:z.string().optional()}},async({limit=20,deck})=>{const s=await load(userId),notes=new Map((s.notes??[]).map((n:any)=>[n.id,n]));const cards=(s.cards??[]).filter((c:any)=>!deck||(notes.get(c.noteId) as any)?.deck===deck).sort((a:any,b:any)=>b.lapses-a.lapses||(a.memory.stability??0)-(b.memory.stability??0)).slice(0,limit).map((c:any)=>({card:c,note:notes.get(c.noteId)}));return content({cards})});
  server.registerTool("bulk_import",{description:"Import French notes from JSON or simple CSV.",inputSchema:{csv:z.string().optional(),json:z.union([z.string(),z.array(z.record(z.string(),z.unknown()))]).optional()}},async({csv,json})=>{let rows:any[]=[];if(json)rows=typeof json==="string"?JSON.parse(json):json;else if(csv)rows=csv.split(/\r?\n/).filter(Boolean).map(line=>{const[lemma,translation]=line.split(",");return{lemma,translation}});return content(await addWords(rows))});
  return server;
}
async function handle(request:Request){const userId=await authenticate(request);if(!userId)return Response.json({error:"Invalid or revoked API key"},{status:401,headers:{"WWW-Authenticate":"Bearer"}});const transport=new WebStandardStreamableHTTPServerTransport();const server=createServer(userId);await server.connect(transport);return transport.handleRequest(request)}
export const GET=handle;export const POST=handle;export const DELETE=handle;
